### ISSUE TITLE
Modded blocks are recorded incorrectly

### ISSUE THREAD

**Issue by zhizhizhiwang** [senseiwells/ServerReplay#71]
The biggest difference from the original version: [Mishang Urban Construction](https://github.com/SolidBlock-cn/mishanguc) installed   
My server load log : [log](https://mclo.gs/PolvjU1)  
My client log : [log](https://mclo.gs/nZH3PSA)  
Everything seems to be working fine when I connect to the server, but when I use the replay mod to load the mcpr file downloaded by the server, the block records are all wrong.   
For example, my walls turned into water, and the sky was filled with blocks that shouldn't be there.    
I didn't find any issues about the bug after adding a mod that can add blocks, so I posted this issue hoping to solve this problem.    
> My native language is Chinese, the above content uses Google Translate.  : )

**Comment by senseiwells** [comment]
Thanks for the report, I have released a more up to date version of ServerReplay for 1.20.1, which you can download [here](https://modrinth.com/mod/server-replay/version/1.2.2+mc1.20.1), see if this fixes your issue.

If not, can you re-produce this issue with the new version then can you able to send a copy of the replay file?
And are you able to reproduce this with just the Mishang Urban Construction mod and it's dependencies (without any of the other mods)? If so, could you also send a copy of that replay file.

You can upload them here (rename the .mcpr files to .zip) or you can upload them here: https://filebin.net/ and send the link

**Comment by zhizhizhiwang** [comment]
Unfortunately, the new version did not solve my problem.   
My mcpr file are in here
[replay_by_local.zip](https://github.com/user-attachments/files/18081457/replay_by_local.zip)
[replay_by_server.zip](https://github.com/user-attachments/files/18081459/replay_by_server.zip)

my server mod list is
```
[22:26:53] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.16.9
[22:26:54] [main/INFO]: Loading 97 mods:
	- architectury 9.2.14
	- brrp_v1 1.0.1
	- easyauth 3.0.19
	   |-- at_favre_lib_bcrypt 0.9.0
	   |-- at_favre_lib_bytes 1.5.0
	   |-- com_mysql_mysql-connector-j 8.0.33
	   |-- de_mkammerer_argon2-jvm 2.11
	   |-- de_mkammerer_argon2-jvm-nolibs 2.11
	   |-- net_java_dev_jna_jna 5.12.1
	   |-- org_iq80_leveldb_leveldb 0.12
	   |-- org_iq80_leveldb_leveldb-api 0.12
	   |-- org_mongodb_bson 4.7.2
	   |-- org_mongodb_mongodb-driver-core 4.7.2
	   |-- org_mongodb_mongodb-driver-sync 4.7.2
	   |-- placeholder-api 2.1.1+1.20
	   \-- server_translations_api 2.0.0+1.20
	        \-- packet_tweaker 0.4.0+1.19.4
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.13.0+kotlin.2.1.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.1.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.1.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.26.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.9.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.1
	   |-- org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-io-core-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.7.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.7.3
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- ftbbackups2 1.0.23
	- ftbchunks 2001.3.1
	- ftblibrary 2001.2.2
	- ftbranks 2001.1.3
	- ftbteams 2001.3.0
	- grieflogger 1.1.5
	- java 21
	- ledger 1.2.8
	- ledger-databases 1.1.1
	   |-- com_h2database_h2 1.4.200
	   |-- mysql_mysql-connector-java 8.0.19
	   \-- org_postgresql_postgresql 42.3.0
	- luckperms 5.4.102
	- minecraft 1.20.1
	- mishanguc 1.3.3
	- polylib 2000.0.3-build.143
	   \-- team_reborn_energy 2.2.0
	- server-replay 1.2.2
	   |-- fabric-permissions-api-v0 0.3.1
	   |-- net_mcbrawls_inject_api 2.2.2
	   \-- net_mcbrawls_inject_http 2.2.2
	- supermartijn642configlib 1.1.8+a
	- worldcomment 0.1.1+1.20.1
	- worldedit 7.2.15+6463-5ca4dff
```   
java is    
```
openjdk 21.0.3 2024-04-16
OpenJDK Runtime Environment (build 21.0.3+9-Ubuntu-1ubuntu120.04.1)
OpenJDK 64-Bit Server VM (build 21.0.3+9-Ubuntu-1ubuntu120.04.1, mixed mode, sharing)
```   
Local pack can be install by [this](https://github.com/zhizhizhiwang/RedStoneHub/releases/download/common_pack/redstone_pack_v1.2_build-2024-11-08.zip)
(with HMCL)

**Comment by zhizhizhiwang** [comment]
local pack without replay mod, I install it by myself(

**Comment by senseiwells** [comment]
Sorry for the very long delay, but I have decided to mark this as won't fix. If someone is able to re-produce this (or similar) for the latest version of the game (that I am supporting) then I will investigate further.

**Comment by zhizhizhiwang** [comment]
Thank you very much for your response. I think this might be caused by converting from a low-version world to a high-version one. If I have time, I will conduct further tests.
